---
title: "statistical_learning"
output: github_document
date: "2024-11-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(glmnet)
set.seed(1031)
```


## try lasso

import and clean birthweight data
```{r}
bwt_df = 
  read_csv("birthweight.csv")|>
  janitor::clean_names()|>
  mutate(
    babysex = 
      case_match(babysex, 
                 1 ~ "male",
                 2 ~ "female"),
    babysex = fct_infreq(babysex),
    
    frace = case_match(frace,
                1 ~ "white",
                2 ~ "black",
                3 ~ "asian",
                4 ~ "puerto rican",
                5 ~ "other"),
    frace = fct_infreq(frace),
    
    mrace = case_match(mrace,
                1 ~ "white",
                2 ~ "black",
                3 ~ "asian",
                4 ~ "puerto rican",
                5 ~ "other"),
    mrace = fct_infreq(mrace)
    )|>
  sample_n(200)
  

```


construct inputs for "glmnet"
```{r}
x = model.matrix(bwt ~., data = bwt_df)[, -1]
y = bwt_df |> pull(bwt)
```


fit lasso for several lambdas
```{r}
lambda = 10^seq(-2, 2.75, by = 0.1)

lasso_fit = 
  glmnet(x = x, y = y, lambda = lambda)

lasso_cv = 
  cv.glmnet(x = x, y = y, lambda = lambda) 

lambda_opt = lasso_cv[["lambda.min"]]
```



usual lasso plot
```{r}
lasso_fit |>
  broom::tidy()|>
  filter(term != "(Intercept)")|>
  select(term, lambda, estimate)|>
  complete(term, lambda, fill = list(estimate = 0))|>
  ggplot(aes(x = lambda, y = estimate, group = term, color = term))+
  geom_vline(xintercept = lambda_opt, color = "pink")+
  geom_line()
```


```{r}
final_lasso_fit = 
  glmnet(x = x, y = y, lambda = lambda_opt)

final_lasso_fit|>
  broom::tidy()
```

look at CV results.
```{r}
lasso_cv|>
  broom::tidy()|>
  ggplot(aes(x = log(lambda,10), y = estimate))+
  geom_point()
```


### Cluster pokemons
```{r}
pokemon_df = 
  read_csv("pokemon.csv")|>
  janitor::clean_names()|>
  select(hp, speed)
```


```{r}
pokemon_df |>
  ggplot(aes(x = hp, y = speed))+
  geom_point()
```

let's use kmeans to cluster these pokemon!
```{r}
kmeans_fit = 
  kmeans(x = pokemon_df, centers = 4)
```

can i plot these results
```{r}
pokemon_df = 
  broom::augment(kmeans_fit,pokemon_df)
```

```{r}
pokemon_df |>
  ggplot(aes(x = hp, y = speed, color = .cluster))+
  geom_point()
```

